### ISSUE TITLE
fatal: remote error: Git repository not found

### ISSUE THREAD

**Issue by ryandesign** [aseprite/skia#16]
When fetching skia's dependencies prior to building skia, the skia common repo fails to sync because the repository appears to have been deleted from the server:
```
$ python3.9 tools/git-sync-deps
fatal: remote error: Git repository not found
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/skia/tools/git-sync-deps", line 131, in git_checkout_to_directory
    subprocess.check_call(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', '--quiet', '--no-checkout', 'https://skia.googlesource.com/common.git', '/path/to/skia/common']' returned non-zero exit status 128.
Skipping "../src".
```
This does not prevent the build from completing successfully.

**Comment by jusw85** [comment]
It was removed from the skia project on 4th May

https://github.com/google/skia/commit/64e74e64977709b2291d3fff1eb4cf67b76db8ae#diff-4cc955bcf0b472353786cc8d8b7d346fb432c091bed099de884885e938392814
