### ISSUE TITLE
bin/fetch-gn returned non-zero exit status of 1

### ISSUE THREAD

**Issue by cheepling** [aseprite/skia#23]
When trying to run `python tools/git-sync-deps`, I receive a series of errors culminating in `subprocess.CalledProcessError: Command '['/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', 'bin/fetch-gn']' returned non-zero exit status 1`.

When running `python3 tools/git-sync-deps`, I receive the alternate error 
`subprocess.CalledProcessError: Command '['/usr/local/bin/python3', 'bin/fetch-gn']' returned non-zero exit status 1`.

All of the other python submodules seem to be compiling fine up to this point.
I am running this in zsh on MacOS Big Sur 11.6.5 .

Full errors:
For `python tools/git-sync-deps`:
```Skipping "../src".
Skipping "bin".
third_party/externals/brotli         @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
third_party/externals/abseil-cpp     @ c5a424a2a21005660b182516eb7a079cd8021699
buildtools                           @ b138e6ce86ae843c42a1a08f37903207bebcca75
third_party/externals/angle2         @ 8718783526307a3fbb35d4c1ad4e8101262a0d73
third_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
third_party/externals/expat          @ a28238bdeebc087071777001245df1876a11f5ee
third_party/externals/dng_sdk        @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
third_party/externals/emsdk          @ fc645b7626ebf86530dbd82fbece74d457e7ae07
third_party/externals/egl-registry   @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
third_party/externals/highway        @ 424360251cdcfc314cfc528f53c872ecd63af0f0
third_party/externals/dawn           @ 088a600b03679cd20991f145173a573ed9c03480
third_party/externals/jinja2         @ ee69aa00ee8536f61db6a451f3858745cf587de6
third_party/externals/markupsafe     @ 0944e71f4b2cb9a871bcbe353f95e889b64a611a
third_party/externals/harfbuzz       @ 8d1b000a3edc90c12267b836b4ef3f81c0e53edc
third_party/externals/icu            @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
third_party/externals/libjpeg-turbo  @ 22f1a22c99e9dde8cd3c72ead333f425c5a7aa77
third_party/externals/freetype       @ f122349b937d7d2b0f8b72f46f60a082ca6006db
...d_party/externals/opengl-registry @ 14b80ebeab022b2c78f84a573f01028c96075553
third_party/externals/libpng         @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
third_party/externals/libwebp        @ 20ef03ee351d4ff03fc5ff3ec4804a879d1b9d5c
third_party/externals/sfntly         @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
third_party/externals/imgui          @ 55d35d8387c15bf0cfd71861df67af8cfbda7456
third_party/externals/oboe           @ b02a12d1dd821118763debec6b83d00a8a0ee419
third_party/externals/libjxl         @ a205468bc5d3a353fb15dae2398a101dff52f2d3
third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
third_party/externals/spirv-tools    @ cb96abbf7affd986016f17dd09f9f971138a922b
third_party/externals/libgifcodec    @ fd59fa92a0c86788dcdd84d091e1ce81eda06a77
third_party/externals/wuffs          @ 600cd96cf47788ee3a74b40a6028b035c9fd6a61
third_party/externals/vulkan-tools   @ fa288188b574d9eee31cd52c5432780b6a46a412
third_party/externals/vulkan-headers @ 76f00ef6cbb1886eb1162d1fa39bee8b51e22ee8
third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
third_party/externals/spirv-headers  @ 82becc8a8a92e509d3d8d635889da0a3c17d0606
third_party/externals/spirv-cross    @ 6a67891418a3f08be63f92726e049dc788e46f5b
third_party/externals/swiftshader    @ 1d450ae99a0f4ade28dd55dac962f8b28d990376
third_party/externals/vulkan-deps    @ 565408992c44e7d969af8c417a0f72730a85c880
third_party/externals/zlib           @ c876c8f87101c5a75f6014b0f832499afeb65b73
Traceback (most recent call last):
  File "bin/fetch-gn", line 31, in <module>
    f.write(urlopen(url).read())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 54] Connection reset by peer>
Traceback (most recent call last):
  File "tools/git-sync-deps", line 272, in <module>
    exit(main(sys.argv[1:]))
  File "tools/git-sync-deps", line 264, in main
    os.path.join(os.path.dirname(deps_file_path), 'bin', 'fetch-gn')])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', 'bin/fetch-gn']' returned non-zero exit status 1 ```


For `python3 tools/git-sync-deps`:


``` Skipping "../src".
Skipping "bin".
third_party/externals/abseil-cpp     @ c5a424a2a21005660b182516eb7a079cd8021699
buildtools                           @ b138e6ce86ae843c42a1a08f37903207bebcca75
third_party/externals/angle2         @ 8718783526307a3fbb35d4c1ad4e8101262a0d73
third_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
third_party/externals/dng_sdk        @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
third_party/externals/brotli         @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
third_party/externals/egl-registry   @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
third_party/externals/expat          @ a28238bdeebc087071777001245df1876a11f5ee
third_party/externals/emsdk          @ fc645b7626ebf86530dbd82fbece74d457e7ae07
third_party/externals/harfbuzz       @ 8d1b000a3edc90c12267b836b4ef3f81c0e53edc
third_party/externals/freetype       @ f122349b937d7d2b0f8b72f46f60a082ca6006db
third_party/externals/imgui          @ 55d35d8387c15bf0cfd71861df67af8cfbda7456
third_party/externals/highway        @ 424360251cdcfc314cfc528f53c872ecd63af0f0
third_party/externals/spirv-headers  @ 82becc8a8a92e509d3d8d635889da0a3c17d0606
third_party/externals/libpng         @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
third_party/externals/dawn           @ 088a600b03679cd20991f145173a573ed9c03480
third_party/externals/jinja2         @ ee69aa00ee8536f61db6a451f3858745cf587de6
third_party/externals/libgifcodec    @ fd59fa92a0c86788dcdd84d091e1ce81eda06a77
third_party/externals/libjxl         @ a205468bc5d3a353fb15dae2398a101dff52f2d3
third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
third_party/externals/icu            @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
third_party/externals/libwebp        @ 20ef03ee351d4ff03fc5ff3ec4804a879d1b9d5c
...d_party/externals/opengl-registry @ 14b80ebeab022b2c78f84a573f01028c96075553
third_party/externals/wuffs          @ 600cd96cf47788ee3a74b40a6028b035c9fd6a61
third_party/externals/oboe           @ b02a12d1dd821118763debec6b83d00a8a0ee419
third_party/externals/zlib           @ c876c8f87101c5a75f6014b0f832499afeb65b73
third_party/externals/vulkan-deps    @ 565408992c44e7d969af8c417a0f72730a85c880
third_party/externals/sfntly         @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
third_party/externals/spirv-cross    @ 6a67891418a3f08be63f92726e049dc788e46f5b
third_party/externals/libjpeg-turbo  @ 22f1a22c99e9dde8cd3c72ead333f425c5a7aa77
third_party/externals/markupsafe     @ 0944e71f4b2cb9a871bcbe353f95e889b64a611a
third_party/externals/swiftshader    @ 1d450ae99a0f4ade28dd55dac962f8b28d990376
third_party/externals/vulkan-headers @ 76f00ef6cbb1886eb1162d1fa39bee8b51e22ee8
third_party/externals/spirv-tools    @ cb96abbf7affd986016f17dd09f9f971138a922b
third_party/externals/vulkan-tools   @ fa288188b574d9eee31cd52c5432780b6a46a412
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/fetch-gn", line 31, in <module>
    f.write(urlopen(url).read())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 54] Connection reset by peer>
Traceback (most recent call last):
  File "tools/git-sync-deps", line 272, in <module>
    exit(main(sys.argv[1:]))
  File "tools/git-sync-deps", line 264, in main
    os.path.join(os.path.dirname(deps_file_path), 'bin', 'fetch-gn')])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', 'bin/fetch-gn']' returned non-zero exit status 1.
```

**Comment by cheepling** [comment]
I put the files from the zip into the deps/skia directory and it seems to be working fine, i'll close the issue if aseprite builds successfully.

**Comment by dacap** [comment]
It looks like a connection problems to download the files (you can keep trying running the same command until it/Internet-connection works), but if you have downloaded the required files from your browser and it worked, that's great too 👍

**Comment by cheepling** [comment]
Thanks for such quick response time, 1150/1536 aseprite files compiled and it's looking like this isn't an issue anymore. I think the issue before was that my python version was outdated

**Comment by cheepling** [comment]
Unfortunately the second last file had an issue compiling, here's the error:
```ld: library not found for -llaf-ft
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
