### ISSUE TITLE
how can I fix this?

### ISSUE THREAD

**Issue by haniissa** [aseprite/skia#27]
`C:\deps\skia>gn gen out/Release-x64 --args="is_debug=false is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false skia_use_sfntly=false skia_use_freetype=true skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_freetype2=false skia_use_system_harfbuzz=false target_cpu=""x64"" cc=""clang"" cxx=""clang++"" clang_win=""c:\deps\llvm"" win_vc=""C:\Program Files\Microsoft Visual Studio\2022\Community\VC"" extra_cflags=[""-MT""]"
Done. Made 98 targets from 54 files in 1183ms`

`
C:\deps\skia>ninja -C out/Release-x64  skia modules
ninja: error: '../../third_party/externals/harfbuzz/src/hb-aat-layout.cc', needed by 'obj/third_party/externals/harfbuzz/src/harfbuzz.hb-aat-layout.obj', missing and no known rule to make it
ninja: Entering directory `out/Release-x64'
`

**Comment by haniissa** [comment]
is any body here?

**Comment by dacap** [comment]
Hi @haniissa, did you run `python tools/git-sync-deps` in your skia directory?

It looks like external projects (in this case harfbuzz) wasn't checked out yet (and the `git-sync-deps` solves that).

**Comment by haniissa** [comment]
Hi @dacap , I use it and give me this message :
C:\deps\skia>python tools/git-sync-deps
Skipping "../src".
Skipping "bin".
third_party/externals/emsdk          @ fc645b7626ebf86530dbd82fbece74d457e7ae07
third_party/externals/imgui          @ 55d35d8387c15bf0cfd71861df67af8cfbda7456
third_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
third_party/externals/libjpeg-turbo  @ 22f1a22c99e9dde8cd3c72ead333f425c5a7aa77
third_party/externals/libpng         @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
third_party/externals/libjxl         @ a205468bc5d3a353fb15dae2398a101dff52f2d3
third_party/externals/freetype       @ f122349b937d7d2b0f8b72f46f60a082ca6006db
third_party/externals/markupsafe     @ 0944e71f4b2cb9a871bcbe353f95e889b64a611a
third_party/externals/dawn           @ 088a600b03679cd20991f145173a573ed9c03480
third_party/externals/libwebp        @ 20ef03ee351d4ff03fc5ff3ec4804a879d1b9d5c
third_party/externals/jinja2         @ ee69aa00ee8536f61db6a451f3858745cf587de6
third_party/externals/zlib           @ c876c8f87101c5a75f6014b0f832499afeb65b73
third_party/externals/libgifcodec    @ fd59fa92a0c86788dcdd84d091e1ce81eda06a77
third_party/externals/wuffs          @ 600cd96cf47788ee3a74b40a6028b035c9fd6a61
third_party/externals/spirv-cross    @ 6a67891418a3f08be63f92726e049dc788e46f5b
third_party/externals/piex           @ bb217acdca1cc0c16b704669dd6f91a1b509c406
third_party/externals/spirv-headers  @ 82becc8a8a92e509d3d8d635889da0a3c17d0606
third_party/externals/spirv-tools    @ cb96abbf7affd986016f17dd09f9f971138a922b
third_party/externals/vulkan-tools   @ fa288188b574d9eee31cd52c5432780b6a46a412
third_party/externals/microhttpd     @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
error: RPC failed; curl 35 Recv failure: Connection was reset
fatal: expected 'packfile'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tools/git-sync-deps", line 135, in git_checkout_to_directory
    [git, 'clone', '--quiet', '--no-checkout', repo, directory])
  File "C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git.bat', 'clone', '--quiet', '--no-checkout', 'https://chromium.googlesource.com/angle/angle.git', 'third_party/externals/angle2']' returned non-zero exit status 128

buildtools                           @ b138e6ce86ae843c42a1a08f37903207bebcca75
third_party/externals/brotli         @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
third_party/externals/abseil-cpp     @ c5a424a2a21005660b182516eb7a079cd8021699
error: RPC failed; curl 92 HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
error: 62403 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Exception in thread Thread-24:
Traceback (most recent call last):
  File "C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tools/git-sync-deps", line 135, in git_checkout_to_directory
    [git, 'clone', '--quiet', '--no-checkout', repo, directory])
  File "C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git.bat', 'clone', '--quiet', '--no-checkout', 'https://chromium.googlesource.com/external/github.com/google/oboe.git', 'third_party/externals/oboe']' returned non-zero exit status 128

third_party/externals/vulkan-headers > 76f00ef6cbb1886eb1162d1fa39bee8b51e22ee8
third_party/externals/vulkan-deps    @ 565408992c44e7d969af8c417a0f72730a85c880
third_party/externals/highway        > 424360251cdcfc314cfc528f53c872ecd63af0f0
error: 7152 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Exception in thread Thread-31:
Traceback (most recent call last):
  File "C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "tools/git-sync-deps", line 135, in git_checkout_to_directory
    [git, 'clone', '--quiet', '--no-checkout', repo, directory])
  File "C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['git.bat', 'clone', '--quiet', '--no-checkout', 'https://swiftshader.googlesource.com/SwiftShader', 'third_party/externals/swiftshader']' returned non-zero exit status 128

third_party/externals/dng_sdk        @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
third_party/externals/expat          @ a28238bdeebc087071777001245df1876a11f5ee
third_party/externals/egl-registry   @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
third_party/externals/sfntly         > b55ff303ea2f9e26702b514cf6a3196a2e3e2974
third_party/externals/harfbuzz       > 8d1b000a3edc90c12267b836b4ef3f81c0e53edc
...d_party/externals/opengl-registry > 14b80ebeab022b2c78f84a573f01028c96075553
third_party/externals/icu            > a0718d4f121727e30b8d52c7a189ebf5ab52421f
Resolving SDK version '3.1.3' to 'sdk-releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit'
Installing SDK 'sdk-releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit'..
Skipped installing node-14.18.2-64bit, already installed.
Skipped installing python-3.9.2-64bit, already installed.
Skipped installing java-8.152-64bit, already installed.
Skipped installing releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit, already installed.
All SDK components already installed: 'sdk-releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit'.
Resolving SDK version '3.1.3' to 'sdk-releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit'
Setting the following tools as active:
   node-14.18.2-64bit
   python-3.9.2-64bit
   java-8.152-64bit
   releases-upstream-2ddc66235392b37e5b33477fd86cbe01a14b8aa2-64bit

Adding directories to PATH:
PATH += C:\deps\skia\third_party\externals\emsdk
PATH += C:\deps\skia\third_party\externals\emsdk\node\14.18.2_64bit\bin
PATH += C:\deps\skia\third_party\externals\emsdk\upstream\emscripten

Setting environment variables:
PATH = C:\deps\skia\third_party\externals\emsdk;C:\deps\skia\third_party\externals\emsdk\node\14.18.2_64bit\bin;C:\deps\skia\third_party\externals\emsdk\upstream\emscripten;C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin;C:\deps\depot_tools\bootstrap-2@3_8_10_chromium_26_bin\python\bin\Scripts;C:\deps\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin;C:\deps\llvm\bin;C:\deps\depot_tools;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\VulkanSDK\1.3.239.0\Bin;C:\python\Scripts\;C:\python\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\PostgreSQL\13\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\SMLNJ\bin\;C:\Program Files\dotnet\;C:\Users\jazmi\AppData\Local\Programs\Python\Python39;C:\Users\jazmi\AppData\Local\Programs\Python\Python39\Scripts;C:\Users\jazmi\OneDrive\Desktop\emsdk;C:\Users\jazmi\.bun\bin;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files\Cloudflare\Cloudflare WARP\;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\6.0\bin;C:\Program Files\PowerShell\7\;C:\Program Files\Git\cmd;C:\Ninja;C:\Users\jazmi\AppData\Local\Programs\Python\Python38\Scripts\;C:\Users\jazmi\AppData\Local\Programs\Python\Python38\;C:\Ruby31-x64\bin;C:\Users\jazmi\.cargo\bin;C:\Users\jazmi\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\jazmi\AppData\Local\Programs\Python\Python39\;C:\Scripts\;C:\;C:\Users\jazmi\AppData\Local\Microsoft\WindowsApps;C:\Users\jazmi\AppData\Local\Programs\Microsoft VS Code\bin;C:\flutter\bin;C:\Users\jazmi\.dotnet\tools;C:\Program Files\heroku\bin;C:\tools\neovim\Neovim\bin;C:\Program Files (x86)\Oni;C:\Exercism;C:\Users\jazmi\AppData\Local\GitHubDesktop\bin;C:\Users\jazmi\AppData\Local\Programs\oh-my-posh\bin;C:\Users\jazmi\AppData\Local\Programs\oh-my-posh\themes;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;C:\tools\neovim\nvim-win64\bin;C:\VulkanSDK\1.3.239.0;C:\Program Files\CMake\bin;C:\Users\jazmi\AppData\Roaming\npm;C:\Users\jazmi\AppData\Roaming\Dashlane\4.6.6.23032\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components
EMSDK = C:/deps/skia/third_party/externals/emsdk
EM_CONFIG = C:\deps\skia\third_party\externals\emsdk\.emscripten
EMSDK_NODE = C:\deps\skia\third_party\externals\emsdk\node\14.18.2_64bit\bin\node.exe
EMSDK_PYTHON = C:\deps\skia\third_party\externals\emsdk\python\3.9.2_64bit\python.exe
JAVA_HOME = C:\deps\skia\third_party\externals\emsdk\java\8.152_64bit
The changes made to environment variables only apply to the currently running shell instance. Use the 'emsdk_env.bat' to re-enter this environment later, or if you'd like to register this environment permanently, rerun this command with the option --permanent.

**Comment by haniissa** [comment]
and I run this command again: 
C:\deps\skia>ninja -C out/Release-x64  skia modules
ninja: Entering directory `out/Release-x64'
[12/1716] compile ../../src/ports/SkFontMgr_android_parser.cpp
FAILED: obj/src/ports/fontmgr_android.SkFontMgr_android_parser.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_ENABLE_SKSL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DXML_STATIC -I../.. -I../../third_party/externals/expat/expat/lib -I../../third_party/expat/include/expat_config -Wno-attributes /bigobj /utf-8 -imsvc "C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/winrt" /O2 /Zc:inline -MT /imsvc C:/deps/skia/third_party/externals/expat/expat/lib /imsvc C:/deps/skia/third_party/expat/include/expat_config  /std:c++17 /GR- /c ../../src/ports/SkFontMgr_android_parser.cpp /Foobj/src/ports/fontmgr_android.SkFontMgr_android_parser.obj /Fd"obj/fontmgr_android_c.pdb"
In file included from ../../src/ports/SkFontMgr_android_parser.cpp:10:
In file included from ../..\include/core/SkFontMgr.h:11:
In file included from ../..\include/core/SkFontArguments.h:11:
In file included from ../..\include/core/SkColor.h:12:
In file included from ../..\include/core/SkScalar.h:11:
In file included from ../..\include/private/SkFloatingPoint.h:16:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\cmath:9:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals.h:9:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(784,1): error: static_assert failed "Error in C++ Standard Library usage."
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 14.0.0 or newer.");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(456,5): note: expanded from macro '_EMIT_STL_ERROR'
    static_assert(false, "Error in C++ Standard Library usage.")
    ^             ~~~~~
1 error generated.
[13/1716] compile ../../src/opts/SkOpts_avx.cpp
FAILED: obj/src/opts/avx.SkOpts_avx.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_ENABLE_SKSL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../.. /arch:AVX -Wno-attributes /bigobj /utf-8 -imsvc "C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/winrt" /O2 /Zc:inline -MT  /std:c++17 /GR- /c ../../src/opts/SkOpts_avx.cpp /Foobj/src/opts/avx.SkOpts_avx.obj /Fd"obj/avx_c.pdb"
In file included from ../../src/opts/SkOpts_avx.cpp:8:
In file included from ../..\src/core/SkOpts.h:13:
In file included from ../..\src/core/SkRasterPipeline.h:11:
In file included from ../..\include/core/SkColor.h:12:
In file included from ../..\include/core/SkScalar.h:11:
In file included from ../..\include/private/SkFloatingPoint.h:16:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\cmath:9:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals.h:9:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(784,1): error: static_assert failed "Error in C++ Standard Library usage."
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 14.0.0 or newer.");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(456,5): note: expanded from macro '_EMIT_STL_ERROR'
    static_assert(false, "Error in C++ Standard Library usage.")
    ^             ~~~~~
1 error generated.
[14/1716] compile ../../src/ports/SkFontMgr_custom_directory.cpp
FAILED: obj/src/ports/fontmgr_custom_directory.SkFontMgr_custom_directory.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_ENABLE_SKSL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../.. -Wno-attributes /bigobj /utf-8 -imsvc "C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/winrt" /O2 /Zc:inline -MT  /std:c++17 /GR- /c ../../src/ports/SkFontMgr_custom_directory.cpp /Foobj/src/ports/fontmgr_custom_directory.SkFontMgr_custom_directory.obj /Fd"obj/fontmgr_custom_directory_c.pdb"
In file included from ../../src/ports/SkFontMgr_custom_directory.cpp:8:
In file included from ../..\include/core/SkStream.h:11:
In file included from ../..\include/core/SkData.h:13:
In file included from ../..\include/core/SkRefCnt.h:13:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\atomic:9:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals.h:9:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(784,1): error: static_assert failed "Error in C++ Standard Library usage."
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 14.0.0 or newer.");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(456,5): note: expanded from macro '_EMIT_STL_ERROR'
    static_assert(false, "Error in C++ Standard Library usage.")
    ^             ~~~~~
1 error generated.
[15/1716] compile ../../src/ports/SkFontMgr_custom_embedded.cpp
FAILED: obj/src/ports/fontmgr_custom_embedded.SkFontMgr_custom_embedded.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_ENABLE_SKSL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../.. -Wno-attributes /bigobj /utf-8 -imsvc "C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/winrt" /O2 /Zc:inline -MT  /std:c++17 /GR- /c ../../src/ports/SkFontMgr_custom_embedded.cpp /Foobj/src/ports/fontmgr_custom_embedded.SkFontMgr_custom_embedded.obj /Fd"obj/fontmgr_custom_embedded_c.pdb"
In file included from ../../src/ports/SkFontMgr_custom_embedded.cpp:8:
In file included from ../..\include/core/SkStream.h:11:
In file included from ../..\include/core/SkData.h:13:
In file included from ../..\include/core/SkRefCnt.h:13:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\atomic:9:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals.h:9:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(784,1): error: static_assert failed "Error in C++ Standard Library usage."
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 14.0.0 or newer.");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(456,5): note: expanded from macro '_EMIT_STL_ERROR'
    static_assert(false, "Error in C++ Standard Library usage.")
    ^             ~~~~~
1 error generated.
[16/1716] compile ../../src/ports/SkFontMgr_custom.cpp
FAILED: obj/src/ports/fontmgr_custom.SkFontMgr_custom.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_ENABLE_SKSL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../.. -Wno-attributes /bigobj /utf-8 -imsvc "C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/winrt" /O2 /Zc:inline -MT  /std:c++17 /GR- /c ../../src/ports/SkFontMgr_custom.cpp /Foobj/src/ports/fontmgr_custom.SkFontMgr_custom.obj /Fd"obj/fontmgr_custom_c.pdb"
In file included from ../../src/ports/SkFontMgr_custom.cpp:8:
In file included from ../..\include/core/SkFontArguments.h:11:
In file included from ../..\include/core/SkColor.h:12:
In file included from ../..\include/core/SkScalar.h:11:
In file included from ../..\include/private/SkFloatingPoint.h:16:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\cmath:9:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals.h:9:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(784,1): error: static_assert failed "Error in C++ Standard Library usage."
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 14.0.0 or newer.");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(456,5): note: expanded from macro '_EMIT_STL_ERROR'
    static_assert(false, "Error in C++ Standard Library usage.")
    ^             ~~~~~
1 error generated.
[17/1716] compile ../../src/ports/SkFontMgr_android.cpp
FAILED: obj/src/ports/fontmgr_android.SkFontMgr_android.obj
"c:\deps\llvm/bin/clang-cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_ENABLE_SKSL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DXML_STATIC -I../.. -I../../third_party/externals/expat/expat/lib -I../../third_party/expat/include/expat_config -Wno-attributes /bigobj /utf-8 -imsvc "C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/winrt" /O2 /Zc:inline -MT /imsvc C:/deps/skia/third_party/externals/expat/expat/lib /imsvc C:/deps/skia/third_party/expat/include/expat_config  /std:c++17 /GR- /c ../../src/ports/SkFontMgr_android.cpp /Foobj/src/ports/fontmgr_android.SkFontMgr_android.obj /Fd"obj/fontmgr_android_c.pdb"
In file included from ../../src/ports/SkFontMgr_android.cpp:10:
In file included from ../..\include/core/SkData.h:13:
In file included from ../..\include/core/SkRefCnt.h:13:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\atomic:9:
In file included from C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals.h:9:
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(784,1): error: static_assert failed "Error in C++ Standard Library usage."
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 14.0.0 or newer.");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\2022\Community\VC/Tools/MSVC/14.34.31933/include\yvals_core.h(456,5): note: expanded from macro '_EMIT_STL_ERROR'
    static_assert(false, "Error in C++ Standard Library usage.")
    ^             ~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
